-Wall == all warnings enabled
-Werror == treat warnings as ERRORS!
CPPFLAGS = --std=c++11 -Wall -Werror -DBOOST_TEST_DYN_LINK
LINKFLAGS = --std=c++11 -lboost_unit_test_framework

lib_SOURCES = \
	../include/LinkedList.h\
	../include/Vector.h

lib_OBJECTS=$(lib_SOURCES:.cpp=.o)

tests_SOURCES = \
	tests_main.cpp \
	LinkedListTests.cpp \
	VectorTests.cpp 

tests_OBJECTS=$(tests_SOURCES:.cpp=.o)

tests_EXECUTABLE = tests_bin

all: tests

%.o : %.cpp
	$(CXX) -c $(CPPFLAGS) $< -o $@

$(tests_EXECUTABLE): $(tests_OBJECTS) $(lib_OBJECTS)
	$(CXX) -o $@ $(tests_OBJECTS) $(lib_OBJECTS) $(LINKFLAGS)

tests: $(tests_EXECUTABLE)
	./$(tests_EXECUTABLE)

.PHONY: clean tests

clean:
	- rm *.o
	- rm tests_bin
